### ISSUE TITLE
Error opening file 'client_secrets.json': No such file or directory

### ISSUE THREAD

**Issue by mackonsti** [brianc118/Google-Calendar-Undo-Import#2]
Hello and thanks for this great script but:

1. On Windows 10 x64 I installed latest Python v3.6.3 to directory C:\Python\
2. I installed as requested the Google APIs and obtained client_secret.json file
3. The sample python file by Google (that obtains 10 next calendar events) works perfectly.
4. In directory D:\Calendar\ I have downloaded your script and also placed client_secret.json there.
5. I run the script but I get this error on DOS window:

```
D:\Calendar>gcal_undo_import.py
The client secrets were invalid:
(Error opening file, D:\\Calendar\\client_secrets.json, No such file or directory, 2)
WARNING: Please configure OAuth 2.0

To make this sample run you will need to populate the client_secrets.json file
found at:

   D:\Calendar\client_secrets.json

with information from the APIs Console <https://code.google.com/apis/console>.
```

I even copied client_secret.json to my main C:\Python\ installation directory before running:

`pip install --upgrade google-api-python-client`

Any help is welcome. Thanks!

**Comment by mackonsti** [comment]
UPDATE:

Despite your main page pointing to Google's instruction to install their Google Client Library:

pip install --upgrade google-api-python-client

I re-run the script in verbose and I detected this interesting bit, that could help:

```
# C:\Python\lib\__pycache__\socketserver.cpython-36.pyc matches C:\Python\lib\socketserver.py
# code object from 'C:\\Python\\lib\\__pycache__\\socketserver.cpython-36.pyc'
import 'socketserver' # <_frozen_importlib_external.SourceFileLoader object at 0x05E8B690>
import 'http.server' # <_frozen_importlib_external.SourceFileLoader object at 0x05E59990>
import 'oauth2client.tools' # <_frozen_importlib_external.SourceFileLoader object at 0x05E597F0>
import 'googleapiclient.sample_tools' # <_frozen_importlib_external.SourceFileLoader object at 0x05D8B450>
The client secrets were invalid:
('Error opening file', 'client_secrets.json', 'No such file or directory', 2)
WARNING: Please configure OAuth 2.0

To make this sample run you will need to populate the client_secrets.json file found at:

   client_secrets.json

with information from the APIs Console <https://code.google.com/apis/console>.

# clear builtins
```

So whilst searching 'googleapiclient.sample_tools' for some ideas (I am not an experienced Python user, just want to undo my ICAL import into my GCalendar) I read another page regarding using Google APIs on GitHub:

> Google Cloud Platform APIs
> 
> If you're working with Google Cloud Platform APIs such as Datastore or Pub/Sub, consider using the Cloud Client Libraries for Python instead. These are the new and idiomatic Python libraries targeted specifically at Google Cloud Platform Services.

So per page: https://github.com/GoogleCloudPlatform/google-cloud-python

I am told to run instead: $ pip install --upgrade google-cloud

...which of course didn't help although the test script "quickstart.py" still runs 100% well... so there is no clear problem with the JSON file?

Your advice is welcome. Thanks.

**Comment by brianc118** [comment]
The error says no such file or directory. Check name of the file client_secrets.json (secrets not secret).

**Comment by mackonsti** [comment]
You are of course, correct. Huge apologies for missing out the 's' at the end of the filename.
Google's instructions say **client_secret.json** and yours **client_secrets.json** and I never returned to confirm your naming convention. Script runs now and returns the calendars added, indeed. Thank you

**Comment by Abdulakhtar** [comment]
the name of file is with s but its not opening in my case
it shows traceback error in lines and modules. how to solve it?
i am doing it with helo_analytics_api_v3.py sample file
